#!/usr/bin/bash
# This code was written by (maroufwani)
if [[ "$id -u" -ne 0 ]]; then
  echo "
Please Run This Programm as Root!
"
  exit 1
fi
printf '\033]2;DDoS/Updating\a'
clear
echo "Updating DDoS Tool..."
sleep 2
cd .. && cd .. && rm -r DDoS && git clone https://github.com/maroufwani/DDoS && cd DDoS && bash install.sh
echo "
Updating..., Finish...!

"
exit 1
